### ISSUE TITLE
Parameterize "@print-object" and other attrs

### ISSUE THREAD

**Issue by infojunkie** [no-chris/chord-symbol-musicxml#13]
Would be great to allow the caller to configure the MusicXML output, especially when it involves ambiguous areas like `@print-object` and `@text` attributes that various softwares may or may not support fully and correctly. In light of [recent MusicXML conversations](https://github.com/w3c/musicxml/issues/369) and recent changes in the OSMD codebase, the following options would be very useful:

- Whether `kind/@text` should contain only the root chord kind or the full chord name (including degrees)
- Whether the various `@print-object` attrs should be on or off

Thanks!

**Comment by no-chris** [comment]
👋🏻 

I think I can see where you are going with this and I understand perfectly why. You probably want to bypass the degrees rendering all-together with `@print-object="no"` and only rely on the `kind@text` to visually describe the chord. Am I right?

That make sense, I'll be surprised to find a software that interprets the rendering attributes of `harmony` perfectly. From my limited testing, MuseScore ignores most of them. OSMD latest changes got into the same confusion that I did with `add/alter/subtract`. I don't know about other software.

So that could be a valid option, yes, but I don't know yet if this is the way... will give it a bit more thought.

**Comment by infojunkie** [comment]
> You probably want to bypass the degrees rendering all-together with @print-object="no" and only rely on the kind@text to visually describe the chord. Am I right?

Yes, precisely. The intent is to create a pragmatic "compatibility mode" with existing systems.

Happy to brainstorm about different approaches, as long as we agree on the underlying principle!

**Comment by no-chris** [comment]
One issue I see with this approach is that you will completely discard the "parenthesis" rendering of the software, and use parenthesis where they are not expected at all.
